name: Build
on:
  push:
    branches:
      - '*'  # Cambiado de '**' a '*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Mantener esto es correcto para el análisis

      - name: Configuración de entorno de python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Cambiado a 3.8 para coincidir con sonar-project.properties

      - name: Instalación de librerías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Correr pruebas con coverage
        id: correr-pruebas
        run: |
          mkdir -p coverage-reports
          python -m coverage run -m unittest discover -s tests
          python -m coverage xml -o coverage-reports/coverage.xml
          python -m coverage report -m

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage-reports/coverage.xml